title: Gingko
description: Some notes about life and work.
meta_description: First think, then do, last summarize.

baseurl: ""
url: https://xautjzd.github.io
excerpt_separator: <!-- more -->
paginate: 20
google_analytics: UA-42925167-1
disqus: false
disqus_shortname: gingko

# Details for the RSS feed generator
author:         'GingKo'
authorTwitter:  'xautjzd'

## when publish github, uncomment this line
remote_theme: xautjzd/jekyll-theme-gingko

# when use local, uncomment this line
# theme: jekyll-theme-gingko

plugins: 
  - jekyll-paginate
  - jekyll-remote-theme
