title: Gingko
description: Some notes about life and work.
meta_description: First think, then do, last summarize.

baseurl: ""
url: https://xautjzd.github.io
permalink: /:year/:month/:day/:title:output_ext
excerpt_separator: <!-- more -->
paginate: 20
google_analytics: G-MD311WEJXY
disqus: false
disqus_shortname: gingko

# Details for the RSS feed generator
author:         'GingKo'
authorTwitter:  'xautjzd'

## when publish github, uncomment this line
remote_theme: xautjzd/jekyll-theme-gingko@0.0.1

# when use local, uncomment this line
# theme: jekyll-theme-gingko

plugins: 
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-archives

jekyll-archives:
  enabled: ['categories', 'tags']
  layout: archive
  permalinks:
    category: '/category/:name/'
